"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 10:57:03.836867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('chain_key', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_chain_seq', 'audit_event', ['chain_key', 'seq'], unique=True)
    op.create_index(op.f('ix_audit_event_case_id'), 'audit_event', ['case_id'], unique=False)
    op.create_table('customer',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name_enc', sa.Text(), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=False),
    sa.Column('phone_index', sa.String(length=64), nullable=False),
    sa.Column('email_enc', sa.Text(), nullable=False),
    sa.Column('email_index', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('risk_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('phone_index')
    )
    op.create_index(op.f('ix_customer_email_index'), 'customer', ['email_index'], unique=False)
    op.create_table('feature_flag',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('otp_challenge',
    sa.Column('phone_index', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenge_phone_index'), 'otp_challenge', ['phone_index'], unique=False)
    op.create_table('policy',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yaml', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('product',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('price_minor', sa.BigInteger(), nullable=False),
    sa.Column('returnable', sa.Boolean(), nullable=False),
    sa.Column('image_uris', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('prompt_version',
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('authority_limit_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('address',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('pincode', sa.String(length=12), nullable=False),
    sa.Column('address_enc', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_customer_id'), 'address', ['customer_id'], unique=False)
    op.create_table('graph',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['staff_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_graph_approved_by'), 'graph', ['approved_by'], unique=False)
    op.create_index(op.f('ix_graph_created_by'), 'graph', ['created_by'], unique=False)
    op.create_table('orders',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('coupon_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_minor >= 0', name='order_total_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_table('policy_rule',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('clause_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rule_policy_id'), 'policy_rule', ['policy_id'], unique=False)
    op.create_table('order_item',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('discount_alloc_minor', sa.BigInteger(), nullable=False),
    sa.Column('final_sale', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_sku'), 'order_item', ['sku'], unique=False)
    op.create_table('return_case',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=False),
    sa.Column('graph_version', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('route', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_case_customer_id'), 'return_case', ['customer_id'], unique=False)
    op.create_index(op.f('ix_return_case_order_id'), 'return_case', ['order_id'], unique=False)
    op.create_index('ix_return_case_status_sla', 'return_case', ['status', 'sla_due_at'], unique=False)
    op.create_table('decision_record',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('record', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_record_case_id'), 'decision_record', ['case_id'], unique=False)
    op.create_table('exchange',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('from_sku', sa.String(length=64), nullable=False),
    sa.Column('to_sku', sa.String(length=64), nullable=False),
    sa.Column('reservation_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_case_id'), 'exchange', ['case_id'], unique=False)
    op.create_table('message',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('redacted_content', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_case_id'), 'message', ['case_id'], unique=False)
    op.create_table('notification',
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_case_id'), 'notification', ['case_id'], unique=False)
    op.create_table('outbox',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_case_id'), 'outbox', ['case_id'], unique=False)
    op.create_index('ix_outbox_status_next', 'outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_table('refund',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gateway_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name='refund_amount_positive'),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_refund_case_id'), 'refund', ['case_id'], unique=False)
    op.create_table('replacement_order',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('new_order_ref', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replacement_order_case_id'), 'replacement_order', ['case_id'], unique=False)
    op.create_table('return_item',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.String(length=32), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('condition_grade', sa.String(length=1), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_item_case_id'), 'return_item', ['case_id'], unique=False)
    op.create_index(op.f('ix_return_item_order_item_id'), 'return_item', ['order_item_id'], unique=False)
    op.create_table('risk_assessment',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessment_case_id'), 'risk_assessment', ['case_id'], unique=False)
    op.create_table('shipment',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('carrier', sa.String(length=32), nullable=False),
    sa.Column('awb', sa.String(length=64), nullable=True),
    sa.Column('pickup_slot', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_case_id'), 'shipment', ['case_id'], unique=False)
    op.create_table('sla_timer',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_timer_case_id'), 'sla_timer', ['case_id'], unique=False)
    op.create_index(op.f('ix_sla_timer_due_at'), 'sla_timer', ['due_at'], unique=False)
    op.create_table('approval',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('requested_action', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['staff_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_record.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_approver_id'), 'approval', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approval_case_id'), 'approval', ['case_id'], unique=False)
    op.create_index(op.f('ix_approval_decision_id'), 'approval', ['decision_id'], unique=False)
    op.create_table('evidence',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('return_item_id', sa.Uuid(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('exif', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_phash'), 'evidence', ['phash'], unique=False)
    op.create_index(op.f('ix_evidence_return_item_id'), 'evidence', ['return_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_return_item_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_phash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_approval_decision_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_case_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_approver_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_sla_timer_due_at'), table_name='sla_timer')
    op.drop_index(op.f('ix_sla_timer_case_id'), table_name='sla_timer')
    op.drop_table('sla_timer')
    op.drop_index(op.f('ix_shipment_case_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_index(op.f('ix_risk_assessment_case_id'), table_name='risk_assessment')
    op.drop_table('risk_assessment')
    op.drop_index(op.f('ix_return_item_order_item_id'), table_name='return_item')
    op.drop_index(op.f('ix_return_item_case_id'), table_name='return_item')
    op.drop_table('return_item')
    op.drop_index(op.f('ix_replacement_order_case_id'), table_name='replacement_order')
    op.drop_table('replacement_order')
    op.drop_index(op.f('ix_refund_case_id'), table_name='refund')
    op.drop_table('refund')
    op.drop_index('ix_outbox_status_next', table_name='outbox')
    op.drop_index(op.f('ix_outbox_case_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_notification_case_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_message_case_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_exchange_case_id'), table_name='exchange')
    op.drop_table('exchange')
    op.drop_index(op.f('ix_decision_record_case_id'), table_name='decision_record')
    op.drop_table('decision_record')
    op.drop_index('ix_return_case_status_sla', table_name='return_case')
    op.drop_index(op.f('ix_return_case_order_id'), table_name='return_case')
    op.drop_index(op.f('ix_return_case_customer_id'), table_name='return_case')
    op.drop_table('return_case')
    op.drop_index(op.f('ix_order_item_sku'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_policy_rule_policy_id'), table_name='policy_rule')
    op.drop_table('policy_rule')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_graph_created_by'), table_name='graph')
    op.drop_index(op.f('ix_graph_approved_by'), table_name='graph')
    op.drop_table('graph')
    op.drop_index(op.f('ix_address_customer_id'), table_name='address')
    op.drop_table('address')
    op.drop_table('staff_user')
    op.drop_table('prompt_version')
    op.drop_table('product')
    op.drop_table('policy')
    op.drop_index(op.f('ix_otp_challenge_phone_index'), table_name='otp_challenge')
    op.drop_table('otp_challenge')
    op.drop_table('feature_flag')
    op.drop_index(op.f('ix_customer_email_index'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_audit_event_case_id'), table_name='audit_event')
    op.drop_index('ix_audit_chain_seq', table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
