"""execution and lifecycle

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 11:46:15.074979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notification', sa.Column('audience', sa.String(length=16), server_default='customer', nullable=False))
    op.add_column('notification', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('sla_timer', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sla_timer', 'kind',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index('ix_sla_timer_case_kind', 'sla_timer', ['case_id', 'kind'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sla_timer_case_kind', table_name='sla_timer')
    # Timers are transient; drop ones whose kind no longer fits the old column.
    op.execute("DELETE FROM sla_timer WHERE length(kind) > 32")
    op.alter_column('sla_timer', 'kind',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('sla_timer', 'resolved_at')
    op.drop_column('notification', 'data')
    op.drop_column('notification', 'audience')
    op.drop_table('webhook_event')
    # ### end Alembic commands ###
