"""human in the loop

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 13:37:04.921607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goodwill',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gateway_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['granted_by'], ['staff_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goodwill_case_id'), 'goodwill', ['case_id'], unique=False)
    op.create_index(op.f('ix_goodwill_granted_by'), 'goodwill', ['granted_by'], unique=False)
    op.create_table('queue_item',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('queue', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['staff_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['return_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_item_assignee_id'), 'queue_item', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_queue_item_case_id'), 'queue_item', ['case_id'], unique=False)
    op.create_index('ix_queue_item_open', 'queue_item', ['queue', 'status', 'priority', 'due_at'], unique=False)
    op.add_column('approval', sa.Column('amount_minor', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('approval', sa.Column('required_approvals', sa.Integer(), server_default='1', nullable=False))
    op.add_column('approval', sa.Column('signoffs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('approval', sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval', 'consumed_at')
    op.drop_column('approval', 'signoffs')
    op.drop_column('approval', 'required_approvals')
    op.drop_column('approval', 'amount_minor')
    op.drop_index('ix_queue_item_open', table_name='queue_item')
    op.drop_index(op.f('ix_queue_item_case_id'), table_name='queue_item')
    op.drop_index(op.f('ix_queue_item_assignee_id'), table_name='queue_item')
    op.drop_table('queue_item')
    op.drop_index(op.f('ix_goodwill_granted_by'), table_name='goodwill')
    op.drop_index(op.f('ix_goodwill_case_id'), table_name='goodwill')
    op.drop_table('goodwill')
    # ### end Alembic commands ###
